PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE KNTLword (
word_id INTEGER PRIMARY KEY,
word TEXT NOT NULL UNIQUE,
word_desc TEXT NOT NULL
);
INSERT INTO KNTLword VALUES(1,'AMATOL','bahan peledak campuran antara trinitrotoluena dan amonium nitrat');
INSERT INTO KNTLword VALUES(2,'BANJOL','ruyung (kayu, besi) tajam untuk membelah kayu');
INSERT INTO KNTLword VALUES(3,'BANTAL','alas kepala, alas duduk, sandaran punggung, dsb yg dijahit spt karung, diisi dng kapuk, sabut, dsb');
INSERT INTO KNTLword VALUES(4,'BANYOL','lucu');
INSERT INTO KNTLword VALUES(5,'BENCOL','berbenjol');
INSERT INTO KNTLword VALUES(6,'BENDOL','pengecualian');
INSERT INTO KNTLword VALUES(7,'BENJOL','bengkak atau bincul (pd dahi atau kepala)');
INSERT INTO KNTLword VALUES(8,'BENSOL','bensol ');
INSERT INTO KNTLword VALUES(9,'BENTIL','bentil ');
INSERT INTO KNTLword VALUES(10,'BENTOH','bantah');
INSERT INTO KNTLword VALUES(11,'BENTOK','kebentok');
INSERT INTO KNTLword VALUES(12,'BENTOL','bintik');
INSERT INTO KNTLword VALUES(13,'BENTOS','organisme yg mendiami daerah dasar perairan');
INSERT INTO KNTLword VALUES(14,'BENTUL','tumbuhan berumbi, daun muda dan tangkai mudanya dapat disayur, umbinya dapat dimakan');
INSERT INTO KNTLword VALUES(15,'BENZOL','campuran benzena dng hidrokarbon aromatik yg diperoleh dr gas batu bara atau ter batu bara');
INSERT INTO KNTLword VALUES(16,'BINTAL','bintil (agak besar)');
INSERT INTO KNTLword VALUES(17,'BINTIL','bintul (bercak) kecil (spt bekas digigit nyamuk)');
INSERT INTO KNTLword VALUES(18,'BINTUL','bengkak kecil pd kulit (krn digigit nyamuk, disengat lebah, dsb)');
INSERT INTO KNTLword VALUES(19,'BONBON','gula');
INSERT INTO KNTLword VALUES(20,'BONCEL','kecil');
INSERT INTO KNTLword VALUES(21,'BONCOL','jendul');
INSERT INTO KNTLword VALUES(22,'BONDOL','burung kecil berkepala putih');
INSERT INTO KNTLword VALUES(23,'BONDOT','berkas');
INSERT INTO KNTLword VALUES(24,'BONGOK','besar (gemuk) tetapi pendek');
INSERT INTO KNTLword VALUES(25,'BONGOL','daulat');
INSERT INTO KNTLword VALUES(26,'BONJOL','bonjol ');
INSERT INTO KNTLword VALUES(27,'BONJOR','kubu');
INSERT INTO KNTLword VALUES(28,'BONTAK','gemuk bulat (tt pipi dsb)');
INSERT INTO KNTLword VALUES(29,'BONTOK','bonto');
INSERT INTO KNTLword VALUES(30,'BONTOT','bungsu');
INSERT INTO KNTLword VALUES(31,'BONYOK','memar dan lunak (tt buah dsb)');
INSERT INTO KNTLword VALUES(32,'BONYOR','bonyor ');
INSERT INTO KNTLword VALUES(33,'BORGOL','belenggu tangan terbuat dr besi, berbentuk bulat, dapat ditutup dan dibuka dng memakai kunci');
INSERT INTO KNTLword VALUES(34,'BORKOL','borkol ');
INSERT INTO KNTLword VALUES(35,'BORTEL','wortel');
INSERT INTO KNTLword VALUES(36,'BUNTAL','gembung');
INSERT INTO KNTLword VALUES(37,'BUNTEL','bungkusan');
INSERT INTO KNTLword VALUES(38,'BUNTIL','lauk yg dibuat dr parutan kelapa muda (biasanya dicampuri ikan teri, diberi bumbu bawang, cabai, lengkuas, asam, garam, dsb), dibungkus dng daun keladi, pepaya, atau daun singkong dan dikukus');
INSERT INTO KNTLword VALUES(39,'CANTEL','sorgum');
INSERT INTO KNTLword VALUES(40,'CANTOL','mencantolkan (men.can.tol.kan), mengaitkan pd');
INSERT INTO KNTLword VALUES(41,'CENDOL','penganan yg dibuat dr tepung beras dsb yg dibentuk dng penyaring, kemudian dicampur dng air gula dan santan (untuk minuman)');
INSERT INTO KNTLword VALUES(42,'CENTIL','suka bergaya (tt gadis)');
INSERT INTO KNTLword VALUES(43,'CONGOK','mencongok (men.co.ngok), berdiri (atau duduk) tegak');
INSERT INTO KNTLword VALUES(44,'CONGOL','mencongol (men.co.ngol), menyembul (menonjol) ke luar');
INSERT INTO KNTLword VALUES(45,'CONGOR','jungur');
INSERT INTO KNTLword VALUES(46,'CONTEK','sontek');
INSERT INTO KNTLword VALUES(47,'CONTOH','barang atau sebagian dr barang yg rupa, macam, dan keadaannya sama dng semua barang yg ada');
INSERT INTO KNTLword VALUES(48,'DENTAL','<i>a</i> berhubungan dng gigi atas dl proses artikulasi suatu bunyi');
INSERT INTO KNTLword VALUES(49,'DOKTOR','gelar kesarjanaan tertinggi yg diberikan oleh perguruan tinggi kpd seorang sarjana yg telah menulis dan mempertahankan disertasinya');
INSERT INTO KNTLword VALUES(50,'DOMPOL','berdompol (ber.dom.pol), bergerombol (tt buah');
INSERT INTO KNTLword VALUES(51,'DONDON','warna atau corak (kain dsb)');
INSERT INTO KNTLword VALUES(52,'DONGOK','pendek gemuk');
INSERT INTO KNTLword VALUES(53,'FANTOM','bentuk khayal tt sesuatu (terutama tt bentuk manusia)');
INSERT INTO KNTLword VALUES(54,'FOETAL','tersia');
INSERT INTO KNTLword VALUES(55,'GANTAL','gulungan daun sirih yg dipakai untuk sesaji dsb');
INSERT INTO KNTLword VALUES(56,'GANTEL','menggantelkan');
INSERT INTO KNTLword VALUES(57,'GANTOL','kait');
INSERT INTO KNTLword VALUES(58,'GENTEL','butir (bulatan spt pil)');
INSERT INTO KNTLword VALUES(59,'GONDOK','gemuk pendek (tt badan, leher, barang)');
INSERT INTO KNTLword VALUES(60,'GONDOL','menggondol (meng.gon.dol), menggonggong (membawa dng mulut)');
INSERT INTO KNTLword VALUES(61,'GONGOK','orang yg mencari nafkah dng berdagang');
INSERT INTO KNTLword VALUES(62,'GONIOM','berdiri tegak lurus');
INSERT INTO KNTLword VALUES(63,'GONJOK','menggonjokkan (meng.gon.jok.kan), memperolokkan');
INSERT INTO KNTLword VALUES(64,'GONTAI','lambat (dr yg lain)');
INSERT INTO KNTLword VALUES(65,'GONTOK','bergontok (ber.gon.tok), berkelahi');
INSERT INTO KNTLword VALUES(66,'GONYEL','menekan');
INSERT INTO KNTLword VALUES(67,'GONYOH','menggonyoh (meng.go.nyoh), menggosok (membersihkan)');
INSERT INTO KNTLword VALUES(68,'GONYOK','pajak atas tanah <i>apanase</i> yg harus dibayar oleh pemerintah desa tsb (di Madura)');
INSERT INTO KNTLword VALUES(69,'GUNTIL','<i>n </i>pundi');
INSERT INTO KNTLword VALUES(70,'HONCOE','pipa lengkung untuk mengisap tembakau yg salah satu ujungnya berbentuk cawan sbg tempat tembakau yg akan disulut');
INSERT INTO KNTLword VALUES(71,'HOSTEL','tempat untuk menginap yg murah (biasanya mendapat bantuan pemerintah) bagi mahasiswa, karyawan yg sedang dl pelatihan dsb');
INSERT INTO KNTLword VALUES(72,'JENDOL','jendul');
INSERT INTO KNTLword VALUES(73,'JONGOS','pembantu rumah tangga (laki');
INSERT INTO KNTLword VALUES(74,'JONJOT','menjonjot (men.jon.jot), mencabut (menjemput) hanya dng sekali cabut atau jemput saja (thd tembakau, kapas, dsb)');
INSERT INTO KNTLword VALUES(75,'JONTOH','dongeng yg bertalian dng adat');
INSERT INTO KNTLword VALUES(76,'JONTOR','bengkak (pd bibir) akibat kena pukul, disengat lebah, dsb');
INSERT INTO KNTLword VALUES(77,'KANCIL','binatang pemakan tanaman yg cepat larinya, berbadan langsing, kaki depan lebih pendek dp kaki belakang, bulunya berwarna cokelat kemerah');
INSERT INTO KNTLword VALUES(78,'KANDEL','tebal');
INSERT INTO KNTLword VALUES(79,'KANDIL','pelita');
INSERT INTO KNTLword VALUES(80,'KANDUL','bakul (keranjang) yg biasa digunakan ketika membuat gambir');
INSERT INTO KNTLword VALUES(81,'KANJAL','terhenti krn terhalang dsb');
INSERT INTO KNTLword VALUES(82,'KANSEL','mengansel (me.ngan.sel), membatalkan');
INSERT INTO KNTLword VALUES(83,'KANTAN','halia hutan yg bunganya dapat dirujak atau digunakan sbg bumbu gulai');
INSERT INTO KNTLword VALUES(84,'KANTAR','berkantaran (ber.kan.tar.an), berkobar');
INSERT INTO KNTLword VALUES(85,'KANTER','menarah atau merimbas (kayu)');
INSERT INTO KNTLword VALUES(86,'KANTIH','benang tenun');
INSERT INTO KNTLword VALUES(87,'KANTIL','bunga cempaka putih, <i>Michelia alba</i>');
INSERT INTO KNTLword VALUES(88,'KANTIN','ruang tempat menjual minuman dan makanan (di sekolah, di kantor, di asrama, dsb)');
INSERT INTO KNTLword VALUES(89,'KANTOR','balai (gedung, rumah, ruang) tempat mengurus suatu pekerjaan (perusahaan dsb)');
INSERT INTO KNTLword VALUES(90,'KANTUK','rasa hendak tidur');
INSERT INTO KNTLword VALUES(91,'KANWIL','tampak dng jelas');
INSERT INTO KNTLword VALUES(92,'KANYON','lembah yg sempit dan dalam dng tepi yg terjal, biasanya ada sungai yg mengalir di dasarnya');
INSERT INTO KNTLword VALUES(93,'KARBOL','benda cair berwarna putih dan berbusa spt air sabun serta berbau harum yg dapat dipakai untuk mematikan kuman penyakit');
INSERT INTO KNTLword VALUES(94,'KARTAL','keadaan (sifat dsb) yg buruk');
INSERT INTO KNTLword VALUES(95,'KARTEL','organisasi perusahaan besar (negara dsb) yg memproduksi barang yg sejenis');
INSERT INTO KNTLword VALUES(96,'KARTON','kertas tebal (untuk kulit buku, gambar, dsb) dng berat dasar antara 150—600 g');
INSERT INTO KNTLword VALUES(97,'KARTOT','tanda merah bekas gigitan atau cubitan pd tubuh');
INSERT INTO KNTLword VALUES(98,'KASTAL','pohon kayu yg tumbuh di gurun atau di tanah yg kering');
INSERT INTO KNTLword VALUES(99,'KASTEL','rumah (benteng) yg dikelilingi parit');
INSERT INTO KNTLword VALUES(100,'KASTIL','kastil ');
INSERT INTO KNTLword VALUES(101,'KASTOR','peti tempat menyimpan dadah');
INSERT INTO KNTLword VALUES(102,'KATROL','alat pengangkat dr besi');
INSERT INTO KNTLword VALUES(103,'KEMBOL','mengembol (me.ngem.bol), menjadi besar krn penuh (tt kantong baju dsb)');
INSERT INTO KNTLword VALUES(104,'KENDAL','pohon yg buahnya lebat berwarna merah muda dan licin, spt buah kersen, cabang');
INSERT INTO KNTLword VALUES(105,'KENDIL','periuk');
INSERT INTO KNTLword VALUES(106,'KENDOR','kendor ');
INSERT INTO KNTLword VALUES(107,'KENSEL','meniadakan');
INSERT INTO KNTLword VALUES(108,'KENTAL','antara cair dan keras');
INSERT INTO KNTLword VALUES(109,'KENTAR','ukuran berat untuk menimbang emas');
INSERT INTO KNTLword VALUES(110,'KENTUM','kereta beroda dua yg dihela orang');
INSERT INTO KNTLword VALUES(111,'KENTUT','gas berbau busuk (gas busuk) yg keluar dr anus');
INSERT INTO KNTLword VALUES(112,'KENYAL','empuk dan berdaya pantul (apabila ditekan kembali ke bentuk semula, spt bola karet)');
INSERT INTO KNTLword VALUES(113,'KINTAL','katak yg dapat menggembungkan perutnya');
INSERT INTO KNTLword VALUES(114,'KINTAR','kintar ');
INSERT INTO KNTLword VALUES(115,'KINTIL','ikut dl perjalanan');
INSERT INTO KNTLword VALUES(116,'KLOTOK','melengkapi dng alat');
INSERT INTO KNTLword VALUES(117,'KOAGEL','gel yg terbentuk dl proses koagulasi');
INSERT INTO KNTLword VALUES(118,'KOMBOR','longgar (tt celana)');
INSERT INTO KNTLword VALUES(119,'KOMPON','halaman tertutup');
INSERT INTO KNTLword VALUES(120,'KOMPOR','perapian untuk memasak yg menggunakan minyak tanah, gas, atau listrik sbg bahan bakar');
INSERT INTO KNTLword VALUES(121,'KOMPOS','pupuk campuran yg terdiri atas bahan organik (spt daun dan jerami yg membusuk) dan kotoran hewan');
INSERT INTO KNTLword VALUES(122,'KONDAI','batu spt kaca');
INSERT INTO KNTLword VALUES(123,'KONDOR','burut');
INSERT INTO KNTLword VALUES(124,'KONFER','terbuat');
INSERT INTO KNTLword VALUES(125,'KONGKO','bercakap');
INSERT INTO KNTLword VALUES(126,'KONGKR','penentuan banyaknya barang yg disediakan untuk suatu tempat (pembeli dsb)');
INSERT INTO KNTLword VALUES(127,'KONGSI','persekutuan dagang');
INSERT INTO KNTLword VALUES(128,'KONIUM','<i>Bio</i> cahaya yg dihasilkan makhluk hidup');
INSERT INTO KNTLword VALUES(129,'KONJEN','bersiap');
INSERT INTO KNTLword VALUES(130,'KONKAF','cekung');
INSERT INTO KNTLword VALUES(131,'KONKUR','sakit dan merah warnanya (tt mata)');
INSERT INTO KNTLword VALUES(132,'KONOID','<i>Dok</i> kelenjar di tengah otak');
INSERT INTO KNTLword VALUES(133,'KONOMI','menjadikan cerai');
INSERT INTO KNTLword VALUES(134,'KONPER','orang yg mampu membaca dan menulis');
INSERT INTO KNTLword VALUES(135,'KONSEP','rancangan atau buram surat dsb');
INSERT INTO KNTLword VALUES(136,'KONSER','pertunjukan musik di depan umum');
INSERT INTO KNTLword VALUES(137,'KONSOL','balok yg satu ujungnya terpasang pd suatu penopang tetap dan ujung lainnya bebas');
INSERT INTO KNTLword VALUES(138,'KONSUL','orang yg diangkat dan ditugasi sbg wakil pemerintah suatu negara dl mengurus kepentingan perdagangan atau perihal warganegaranya di negara lain');
INSERT INTO KNTLword VALUES(139,'KONSUM','memiliki bentuk tubuh');
INSERT INTO KNTLword VALUES(140,'KONTAK','hubungan satu dng yg lain');
INSERT INTO KNTLword VALUES(141,'KONTAL','tiruan bunyi katak "kang, kang"');
INSERT INTO KNTLword VALUES(142,'KONTAN','tunai (tt pembayaran)');
INSERT INTO KNTLword VALUES(143,'KONTEN','hambar (tidak sedap) rasanya (lagi) krn sudah kering atau busuk (tt tembakau)');
INSERT INTO KNTLword VALUES(144,'KONTER','melawan');
INSERT INTO KNTLword VALUES(145,'KONTES','perlombaan (kecantikan dsb)');
INSERT INTO KNTLword VALUES(146,'KONTET','tidak dapat tumbuh menjadi besar');
INSERT INTO KNTLword VALUES(147,'KONTIN','lenggak');
INSERT INTO KNTLword VALUES(148,'KONTRA','dl keadaan tidak setuju');
INSERT INTO KNTLword VALUES(149,'KONTUR','garis bentuk');
INSERT INTO KNTLword VALUES(150,'KONVOI','iring');
INSERT INTO KNTLword VALUES(151,'KONYAK','brendi Prancis berkualitas terbaik');
INSERT INTO KNTLword VALUES(152,'KONYAL','markisa');
INSERT INTO KNTLword VALUES(153,'KONYAN','perayaan tahun baru Cina');
INSERT INTO KNTLword VALUES(154,'KONYOL','tidak sopan');
INSERT INTO KNTLword VALUES(155,'KOPBAL','sundulan thd bola (dl sepak bola)');
INSERT INTO KNTLword VALUES(156,'KOPRAL','pangkat golongan tamtama dl ketentaraan, satu tingkat di bawah bintara dan satu tingkat di atas prajurit, yg mencakupi kopral kepala, kopral satu, dan kopral dua');
INSERT INTO KNTLword VALUES(157,'KOPROK','permainan dadu kocok');
INSERT INTO KNTLword VALUES(158,'KOPROL','gerakan berguling ke depan');
INSERT INTO KNTLword VALUES(159,'KOPYOK','mengopyok (me.ngop.yok), mengocok');
INSERT INTO KNTLword VALUES(160,'KOPYOR','lunak dan hancur (tt bagian daging kelapa)');
INSERT INTO KNTLword VALUES(161,'KORDON','garis pelindung');
INSERT INTO KNTLword VALUES(162,'KORION','<i>Dok</i> selaput terluar pembungkus janin');
INSERT INTO KNTLword VALUES(163,'KORNEL','kolonel');
INSERT INTO KNTLword VALUES(164,'KORPUL','(penyakit) kekurangan kadar hemoglobin di dl darah');
INSERT INTO KNTLword VALUES(165,'KORSEL','kuda');
INSERT INTO KNTLword VALUES(166,'KORWIL','unsur logam radioaktif berderajat tiga, menyerupai lantanum dl sifat kimiawinya dan ditemukan pd bijih besi');
INSERT INTO KNTLword VALUES(167,'KOSMOS','jagat raya');
INSERT INTO KNTLword VALUES(168,'KOSTUM','pakaian khusus (dapat pula merupakan pakaian seragam) bagi perseorangan, regu olahraga, rombongan, kesatuan, dsb dl upacara, pertunjukan, dsb');
INSERT INTO KNTLword VALUES(169,'KRATON','bersenda gurau');
INSERT INTO KNTLword VALUES(170,'KRESOL','zat antiseptik turunan fenol yg diperoleh dr dl ter batubara');
INSERT INTO KNTLword VALUES(171,'KTATOR','tempat mencanai');
INSERT INTO KNTLword VALUES(172,'KUATOR','atlet olahraga dayung');
INSERT INTO KNTLword VALUES(173,'KUNTAU','pencak cara Cina');
INSERT INTO KNTLword VALUES(174,'KUNTIT','menguntit (me.ngun.tit), mengikut (dr belakang)');
INSERT INTO KNTLword VALUES(175,'KUNTUL','tidak berekor');
INSERT INTO KNTLword VALUES(176,'KUNTUM','kuncup bunga yg hampir mekar (berkembang');
INSERT INTO KNTLword VALUES(177,'KUSTOS','karangan bunga');
INSERT INTO KNTLword VALUES(178,'LENTOK','terkulai ke sisi (spt sumbu pelita, spt kepala orang yg pingsan)');
INSERT INTO KNTLword VALUES(179,'LONCOS','semakin ke ujung semakin runcing (spt kerucut)');
INSERT INTO KNTLword VALUES(180,'LONDON','tersangkut');
INSERT INTO KNTLword VALUES(181,'LONGOK','melongok (me.lo.ngok), melihat dng mengeluarkan kepala (melalui jendela dsb)');
INSERT INTO KNTLword VALUES(182,'LONJOR','batang (kata penggolong bagi barang yg panjang)');
INSERT INTO KNTLword VALUES(183,'LONTAI','melontai (me.lon.tai), berkeluk (tt garis dsb)');
INSERT INTO KNTLword VALUES(184,'LONTAK','luka panjang pd kulit (bekas kena cambuk)');
INSERT INTO KNTLword VALUES(185,'LONTAR','melontar (me.lon.tar), melempar');
INSERT INTO KNTLword VALUES(186,'LONTOK','pendek dan besar (gemuk)');
INSERT INTO KNTLword VALUES(187,'LONTOS','lembah');
INSERT INTO KNTLword VALUES(188,'LONYOK','lodoh kena api atau siraman air panas');
INSERT INTO KNTLword VALUES(189,'MANTEL','baju panjang (biasanya dr bahan kain tebal), berlengan atau tidak berlengan untuk menyelubungi tubuh');
INSERT INTO KNTLword VALUES(190,'MANTOL','mantol ');
INSERT INTO KNTLword VALUES(191,'MANTUL','<i>cak</i> berdiri di atas kaki sendiri');
INSERT INTO KNTLword VALUES(192,'MENTAL','terpelanting');
INSERT INTO KNTLword VALUES(193,'MENTOK','terantuk (pd)');
INSERT INTO KNTLword VALUES(194,'MENTOL','terna tahunan, suku <i>Lamiaceae</i> yg membentuk stolon, bagian tanaman seluruhnya mengandung minyak asiri yg berbau harum dan dapat diekstrak dng penyulingan, setelah didinginkan menghasilkan mentol');
INSERT INTO KNTLword VALUES(195,'MENTOR','pembimbing atau pengasuh (biasanya untuk mahasiswa)');
INSERT INTO KNTLword VALUES(196,'MENTUL','perhiasan yg dipasang pd rambut atau sanggul, berupa tusuk sanggul bertangkai panjang dng hiasan kuntum bunga bermata (intan, berlian, atau permata imitasi) pd bagian atasnya dan dapat bergerak berayun');
INSERT INTO KNTLword VALUES(197,'MONCOR','mengalir ke luar');
INSERT INTO KNTLword VALUES(198,'MONDOK','pendek gemuk (tt bentuk sesuatu)');
INSERT INTO KNTLword VALUES(199,'MONGOL','gelar bangsawan Bugis');
INSERT INTO KNTLword VALUES(200,'MONIAL','tiruan bunyi rumput kering diinjak, kain digunting, dsb');
INSERT INTO KNTLword VALUES(201,'MONROE','bubukan (hitam, biru, dsb) untuk memalit kening (bulu mata) atau disapukan di sekeliling mata');
INSERT INTO KNTLword VALUES(202,'MONTIR','orang yg pekerjaannya memasang, memperbaiki, dsb mesin kendaraan bermotor, dsb yg rusak');
INSERT INTO KNTLword VALUES(203,'MONTIT','lokomotif kereta api perkebunan');
INSERT INTO KNTLword VALUES(204,'MONTOK','gemuk berisi');
INSERT INTO KNTLword VALUES(205,'MONYOS','mendapat malu (krn kalah dsb)');
INSERT INTO KNTLword VALUES(206,'MUNTUL','tumpul');
INSERT INTO KNTLword VALUES(207,'NAFTOL','<i>Kim</i> zat kristal antiseptik C10H7OH dr ter batu bara, terdapat dl dua bentuk, alfa dan beta');
INSERT INTO KNTLword VALUES(208,'NONGOL','muncul, datang');
INSERT INTO KNTLword VALUES(209,'NONTAX','orang yg pekerjaannya memepat dan menata rambut (putri raja pd zaman dulu dsb)');
INSERT INTO KNTLword VALUES(210,'NONTES','terletak membujur');
INSERT INTO KNTLword VALUES(211,'NONTON','hasil membeli');
INSERT INTO KNTLword VALUES(212,'PANTUL','memantul (me.man.tul), menganjal (spt bola dilemparkan ke dinding)');
INSERT INTO KNTLword VALUES(213,'PENTAL','terpental (ter.pen.tal), terpelanting jauh');
INSERT INTO KNTLword VALUES(214,'PENTOL','sesuatu (bentuk) yg menonjol (agak besar)');
INSERT INTO KNTLword VALUES(215,'PESTOL','pistol');
INSERT INTO KNTLword VALUES(216,'PINTAL','berpintal (ber.pin.tal), berpilin (tt tali, dawai, dsb)');
INSERT INTO KNTLword VALUES(217,'PINTIL','untingan benang');
INSERT INTO KNTLword VALUES(218,'PISTOL','senjata api genggam yg pendek dan kecil');
INSERT INTO KNTLword VALUES(219,'PODSOL','sobek atau retas (tt barang tenunan, kelim, jahitan, dsb)');
INSERT INTO KNTLword VALUES(220,'POKROL','pembela atau wakil orang yg beperkara (dl pengadilan)');
INSERT INTO KNTLword VALUES(221,'PONDOH','nama salak yg daging buahnya empuk, spt embut, rasanya tidak sepet dan tidak masam');
INSERT INTO KNTLword VALUES(222,'PONDOK','bangunan untuk tempat sementara (spt yg didirikan di ladang, di hutan, dsb)');
INSERT INTO KNTLword VALUES(223,'PONSEL','pasang surut kehidupan');
INSERT INTO KNTLword VALUES(224,'PONTEN','angka (biji, nilai) kepandaian atau angka pertandingan (perlombaan)');
INSERT INTO KNTLword VALUES(225,'PONTOH','gelang besar dr emas atau perak yg berukir naga atau merak yg dipakai di lengan atas (di atas siku) atau di atas pergelangan tangan');
INSERT INTO KNTLword VALUES(226,'PONTON','sampan yg rendah dan lebar untuk menggalang atau menyangga jembatan darurat dsb');
INSERT INTO KNTLword VALUES(227,'PORTAL','pintu gerbang');
INSERT INTO KNTLword VALUES(228,'POSTEL','orang yg berpendidikan perguruan tinggi');
INSERT INTO KNTLword VALUES(229,'PUNTAL','berpuntal');
INSERT INTO KNTLword VALUES(230,'PUNTUL','tumpul');
INSERT INTO KNTLword VALUES(231,'RENTAL','persewaan');
INSERT INTO KNTLword VALUES(232,'RONDOK','berondok (be.ron.dok), bersembunyi dng berjongkok di balik semak dsb');
INSERT INTO KNTLword VALUES(233,'RONGOS','merongos (me.ro.ngos), mudah (lekas) marah');
INSERT INTO KNTLword VALUES(234,'RONGOT','rongot ');
INSERT INTO KNTLword VALUES(235,'RONTAL','bersanak saudara');
INSERT INTO KNTLword VALUES(236,'RONTEK','bendera kecil yg dihiaskan pd tombak');
INSERT INTO KNTLword VALUES(237,'RONTOK','jatuh atau gugur dl jumlah yg banyak (tt buah');
INSERT INTO KNTLword VALUES(238,'RONYOK','renyuk');
INSERT INTO KNTLword VALUES(239,'SENTAL','menyental (me.nyen.tal), menggosok kuat');
INSERT INTO KNTLword VALUES(240,'SENTIL','tampak tersembul sedikit di antara bibir (sugi, gula');
INSERT INTO KNTLword VALUES(241,'SENTOL','pendek atau gemuk');
INSERT INTO KNTLword VALUES(242,'SENTUL','pohon, buahnya dapat dimakan, masam rasanya, kayunya dibuat papan');
INSERT INTO KNTLword VALUES(243,'SINEOL','enkaliptol');
INSERT INTO KNTLword VALUES(244,'SINTAL','gemuk padat atau padat berisi (tt tubuh)');
INSERT INTO KNTLword VALUES(245,'SINTIL','sebutan atau panggilan untuk anak laki');
INSERT INTO KNTLword VALUES(246,'SISTOL','melaksanakan');
INSERT INTO KNTLword VALUES(247,'SOFBOL','keadaan damai');
INSERT INTO KNTLword VALUES(248,'SOMBOL','menyombol (me.nyom.bol), menyuapi (makanan dsb) dng paksa');
INSERT INTO KNTLword VALUES(249,'SONDOK','gombak di dahi');
INSERT INTO KNTLword VALUES(250,'SONDOL','sondol ');
INSERT INTO KNTLword VALUES(251,'SONGEL','tersongel');
INSERT INTO KNTLword VALUES(252,'SONTAK','sompek');
INSERT INTO KNTLword VALUES(253,'SONTEK','menyontek');
INSERT INTO KNTLword VALUES(254,'SONTOK','pendek');
INSERT INTO KNTLword VALUES(255,'SOSIOL','berfungsi sbg adjektiva, tetapi tidak dapat berinfleksi spt adjektiva biasa');
INSERT INTO KNTLword VALUES(256,'SOSPOL','memulangkan ke negara asal');
INSERT INTO KNTLword VALUES(257,'SUNTIL','peredaran ulang suatu masa');
INSERT INTO KNTLword VALUES(258,'TOKTOK','batang kayu yg berongga (terdapat di surau dsb) yg dipukul untuk memanggil orang agar salat, berkumpul, dsb');
INSERT INTO KNTLword VALUES(259,'TOMBOL','alat (knop) pd mesin dsb, yg gerak tekan atau gerak tariknya dapat menjalankan, menghentikan, atau mengubah gerak pd mesin');
INSERT INTO KNTLword VALUES(260,'TONGOL','menongol (me.no.ngol), menyembulkan kepala');
INSERT INTO KNTLword VALUES(261,'TONJOK','tinju');
INSERT INTO KNTLword VALUES(262,'TONJOL','jendul (di kulit, di dahi, dsb)');
INSERT INTO KNTLword VALUES(263,'TONSIL','amandel');
INSERT INTO KNTLword VALUES(264,'TONTON','menonton (me.non.ton), melihat (pertunjukan, gambar hidup, dsb)');
INSERT INTO KNTLword VALUES(265,'TORTOR','tarian suku Batak yg dilakukan pd upacara menggali tulang');
INSERT INTO KNTLword VALUES(266,'WORTEL','tanaman sayuran berakar pasak berdaging, berwarna kuning jingga, kaya akan zat gula, vitamin, dan garam mineral');
COMMIT;
