PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE KNTLword (
word_id INTEGER PRIMARY KEY,
word TEXT NOT NULL UNIQUE,
word_desc TEXT NOT NULL
);
INSERT INTO KNTLword VALUES(1,'AMATOL','bahan peledak campuran antara trinitrotoluena dan amonium nitrat');
INSERT INTO KNTLword VALUES(2,'BANJOL','tiruan bunyi benda, spt kopor jatuh ke tanah');
INSERT INTO KNTLword VALUES(3,'BANTAL','alas kepala, alas duduk, sandaran punggung, dsb yg dijahit spt karung, diisi dng kapuk, sabut, dsb');
INSERT INTO KNTLword VALUES(4,'BANYOL','lucu');
INSERT INTO KNTLword VALUES(5,'BENCOL','berbenjol');
INSERT INTO KNTLword VALUES(6,'BENDOL','bercerita kpd');
INSERT INTO KNTLword VALUES(7,'BENJOL','bengkak atau bincul (pd dahi atau kepala)');
INSERT INTO KNTLword VALUES(8,'BENSOL','bensol ');
INSERT INTO KNTLword VALUES(9,'BENTIL','bentil ');
INSERT INTO KNTLword VALUES(10,'BENTOH','bantah');
INSERT INTO KNTLword VALUES(11,'BENTOK','kebentok');
INSERT INTO KNTLword VALUES(12,'BENTOL','bintik');
INSERT INTO KNTLword VALUES(13,'BENTOS','organisme yg mendiami daerah dasar perairan');
INSERT INTO KNTLword VALUES(14,'BENTUL','tumbuhan berumbi, daun muda dan tangkai mudanya dapat disayur, umbinya dapat dimakan');
INSERT INTO KNTLword VALUES(15,'BENZOL','campuran benzena dng hidrokarbon aromatik yg diperoleh dr gas batu bara atau ter batu bara');
INSERT INTO KNTLword VALUES(16,'BINTAL','bintil (agak besar)');
INSERT INTO KNTLword VALUES(17,'BINTIL','bintul (bercak) kecil (spt bekas digigit nyamuk)');
INSERT INTO KNTLword VALUES(18,'BINTUL','bengkak kecil pd kulit (krn digigit nyamuk, disengat lebah, dsb)');
INSERT INTO KNTLword VALUES(19,'BONBON','gula');
INSERT INTO KNTLword VALUES(20,'BONCEL','kecil');
INSERT INTO KNTLword VALUES(21,'BONCOL','jendul');
INSERT INTO KNTLword VALUES(22,'BONDOL','burung kecil berkepala putih');
INSERT INTO KNTLword VALUES(23,'BONDOT','berkas');
INSERT INTO KNTLword VALUES(24,'BONGOK','besar (gemuk) tetapi pendek');
INSERT INTO KNTLword VALUES(25,'BONGOL','orang yg (sedang) diburu (oleh polisi)');
INSERT INTO KNTLword VALUES(26,'BONJOL','bonjol ');
INSERT INTO KNTLword VALUES(27,'BONJOR','kubu');
INSERT INTO KNTLword VALUES(28,'BONTAK','gemuk bulat (tt pipi dsb)');
INSERT INTO KNTLword VALUES(29,'BONTOK','bonto');
INSERT INTO KNTLword VALUES(30,'BONTOT','bungsu');
INSERT INTO KNTLword VALUES(31,'BONYOK','memar dan lunak (tt buah dsb)');
INSERT INTO KNTLword VALUES(32,'BONYOR','bonyor ');
INSERT INTO KNTLword VALUES(33,'BORGOL','belenggu tangan terbuat dr besi, berbentuk bulat, dapat ditutup dan dibuka dng memakai kunci');
INSERT INTO KNTLword VALUES(34,'BORKOL','borkol ');
INSERT INTO KNTLword VALUES(35,'BORTEL','wortel');
INSERT INTO KNTLword VALUES(36,'BUNTAL','gembung');
INSERT INTO KNTLword VALUES(37,'BUNTEL','bungkusan');
INSERT INTO KNTLword VALUES(38,'BUNTIL','lauk yg dibuat dr parutan kelapa muda (biasanya dicampuri ikan teri, diberi bumbu bawang, cabai, lengkuas, asam, garam, dsb), dibungkus dng daun keladi, pepaya, atau daun singkong dan dikukus');
INSERT INTO KNTLword VALUES(39,'CANTEL','sorgum');
INSERT INTO KNTLword VALUES(40,'CANTOL','mencantolkan (men.can.tol.kan), mengaitkan pd');
INSERT INTO KNTLword VALUES(41,'CENDOL','penganan yg dibuat dr tepung beras dsb yg dibentuk dng penyaring, kemudian dicampur dng air gula dan santan (untuk minuman)');
INSERT INTO KNTLword VALUES(42,'CENTIL','suka bergaya (tt gadis)');
INSERT INTO KNTLword VALUES(43,'CONGOK','mencongok (men.co.ngok), berdiri (atau duduk) tegak');
INSERT INTO KNTLword VALUES(44,'CONGOL','mencongol (men.co.ngol), menyembul (menonjol) ke luar');
INSERT INTO KNTLword VALUES(45,'CONGOR','jungur');
INSERT INTO KNTLword VALUES(46,'CONTEK','sontek');
INSERT INTO KNTLword VALUES(47,'CONTOH','barang atau sebagian dr barang yg rupa, macam, dan keadaannya sama dng semua barang yg ada');
INSERT INTO KNTLword VALUES(48,'DENTAL','<i>a</i> berhubungan dng gigi atas dl proses artikulasi suatu bunyi');
INSERT INTO KNTLword VALUES(49,'DOKTOR','gelar kesarjanaan tertinggi yg diberikan oleh perguruan tinggi kpd seorang sarjana yg telah menulis dan mempertahankan disertasinya');
INSERT INTO KNTLword VALUES(50,'DOMPOL','berdompol (ber.dom.pol), bergerombol (tt buah');
INSERT INTO KNTLword VALUES(51,'DONDON','warna atau corak (kain dsb)');
INSERT INTO KNTLword VALUES(52,'DONGOK','pendek gemuk');
INSERT INTO KNTLword VALUES(53,'FANTOM','bentuk khayal tt sesuatu (terutama tt bentuk manusia)');
INSERT INTO KNTLword VALUES(54,'FOETAL','menggenangi');
INSERT INTO KNTLword VALUES(55,'GANTAL','gulungan daun sirih yg dipakai untuk sesaji dsb');
INSERT INTO KNTLword VALUES(56,'GANTEL','menggantelkan');
INSERT INTO KNTLword VALUES(57,'GANTOL','kait');
INSERT INTO KNTLword VALUES(58,'GENTEL','butir (bulatan spt pil)');
INSERT INTO KNTLword VALUES(59,'GONDOK','gemuk pendek (tt badan, leher, barang)');
INSERT INTO KNTLword VALUES(60,'GONDOL','menggondol (meng.gon.dol), menggonggong (membawa dng mulut)');
INSERT INTO KNTLword VALUES(61,'GONGOK','latihan pembiasaan untuk menguasai kecakapan tertentu terutama pd hewan (spt anjing pelacak, kuda)');
INSERT INTO KNTLword VALUES(62,'GONIOM','alat untuk permainan congklak');
INSERT INTO KNTLword VALUES(63,'GONJOK','menggonjokkan (meng.gon.jok.kan), memperolokkan');
INSERT INTO KNTLword VALUES(64,'GONTAI','lambat (dr yg lain)');
INSERT INTO KNTLword VALUES(65,'GONTOK','bergontok (ber.gon.tok), berkelahi');
INSERT INTO KNTLword VALUES(66,'GONYEL','menekan');
INSERT INTO KNTLword VALUES(67,'GONYOH','menggonyoh (meng.go.nyoh), menggosok (membersihkan)');
INSERT INTO KNTLword VALUES(68,'GONYOK','pusaka asal');
INSERT INTO KNTLword VALUES(69,'GUNTIL','<i>n </i>pundi');
INSERT INTO KNTLword VALUES(70,'HONCOE','pipa lengkung untuk mengisap tembakau yg salah satu ujungnya berbentuk cawan sbg tempat tembakau yg akan disulut');
INSERT INTO KNTLword VALUES(71,'HOSTEL','tempat untuk menginap yg murah (biasanya mendapat bantuan pemerintah) bagi mahasiswa, karyawan yg sedang dl pelatihan dsb');
INSERT INTO KNTLword VALUES(73,'JENDOL','jendul');
INSERT INTO KNTLword VALUES(74,'JONGOS','pembantu rumah tangga (laki');
INSERT INTO KNTLword VALUES(75,'JONJOT','menjonjot (men.jon.jot), mencabut (menjemput) hanya dng sekali cabut atau jemput saja (thd tembakau, kapas, dsb)');
INSERT INTO KNTLword VALUES(76,'JONTOH','dongeng yg bertalian dng adat');
INSERT INTO KNTLword VALUES(77,'JONTOR','bengkak (pd bibir) akibat kena pukul, disengat lebah, dsb');
INSERT INTO KNTLword VALUES(78,'KANCIL','binatang pemakan tanaman yg cepat larinya, berbadan langsing, kaki depan lebih pendek dp kaki belakang, bulunya berwarna cokelat kemerah');
INSERT INTO KNTLword VALUES(79,'KANDEL','tebal');
INSERT INTO KNTLword VALUES(80,'KANDIL','pelita');
INSERT INTO KNTLword VALUES(81,'KANDUL','bakul (keranjang) yg biasa digunakan ketika membuat gambir');
INSERT INTO KNTLword VALUES(82,'KANJAL','terhenti krn terhalang dsb');
INSERT INTO KNTLword VALUES(83,'KANSEL','mengansel (me.ngan.sel), membatalkan');
INSERT INTO KNTLword VALUES(84,'KANTAN','halia hutan yg bunganya dapat dirujak atau digunakan sbg bumbu gulai');
INSERT INTO KNTLword VALUES(85,'KANTAR','berkantaran (ber.kan.tar.an), berkobar');
INSERT INTO KNTLword VALUES(86,'KANTER','membunuh (mem.bu.nuh), menghilangkan (menghabisi');
INSERT INTO KNTLword VALUES(87,'KANTIH','benang tenun');
INSERT INTO KNTLword VALUES(88,'KANTIL','bunga cempaka putih, <i>Michelia alba</i>');
INSERT INTO KNTLword VALUES(89,'KANTIN','ruang tempat menjual minuman dan makanan (di sekolah, di kantor, di asrama, dsb)');
INSERT INTO KNTLword VALUES(90,'KANTOR','balai (gedung, rumah, ruang) tempat mengurus suatu pekerjaan (perusahaan dsb)');
INSERT INTO KNTLword VALUES(91,'KANTUK','rasa hendak tidur');
INSERT INTO KNTLword VALUES(92,'KANWIL','kelakar');
INSERT INTO KNTLword VALUES(93,'KANYON','lembah yg sempit dan dalam dng tepi yg terjal, biasanya ada sungai yg mengalir di dasarnya');
INSERT INTO KNTLword VALUES(94,'KARBOL','benda cair berwarna putih dan berbusa spt air sabun serta berbau harum yg dapat dipakai untuk mematikan kuman penyakit');
INSERT INTO KNTLword VALUES(95,'KARTAL','fisika yg berhubungan dng perancangan, pembuatan, dan kerja peranti aerodinamik');
INSERT INTO KNTLword VALUES(96,'KARTEL','organisasi perusahaan besar (negara dsb) yg memproduksi barang yg sejenis');
INSERT INTO KNTLword VALUES(97,'KARTON','kertas tebal (untuk kulit buku, gambar, dsb) dng berat dasar antara 150—600 g');
INSERT INTO KNTLword VALUES(98,'KARTOT','itik yg berasal dr daerah Alabio (Kalimantan Selatan) dan unggul dl kemampuan bertelur');
INSERT INTO KNTLword VALUES(99,'KASTAL','pohon kayu yg tumbuh di gurun atau di tanah yg kering');
INSERT INTO KNTLword VALUES(100,'KASTEL','rumah (benteng) yg dikelilingi parit');
INSERT INTO KNTLword VALUES(101,'KASTIL','kastil ');
INSERT INTO KNTLword VALUES(102,'KASTOR','lapisan udara yg melingkupi bumi');
INSERT INTO KNTLword VALUES(103,'KATROL','alat pengangkat dr besi');
INSERT INTO KNTLword VALUES(104,'KEMBOL','mengembol (me.ngem.bol), menjadi besar krn penuh (tt kantong baju dsb)');
INSERT INTO KNTLword VALUES(105,'KENDAL','pohon yg buahnya lebat berwarna merah muda dan licin, spt buah kersen, cabang');
INSERT INTO KNTLword VALUES(106,'KENDIL','periuk');
INSERT INTO KNTLword VALUES(107,'KENDOR','kendor ');
INSERT INTO KNTLword VALUES(108,'KENSEL','meniadakan');
INSERT INTO KNTLword VALUES(109,'KENTAL','antara cair dan keras');
INSERT INTO KNTLword VALUES(110,'KENTAR','ukuran berat untuk menimbang emas');
INSERT INTO KNTLword VALUES(111,'KENTUM','berdekut');
INSERT INTO KNTLword VALUES(112,'KENTUT','gas berbau busuk (gas busuk) yg keluar dr anus');
INSERT INTO KNTLword VALUES(113,'KENYAL','empuk dan berdaya pantul (apabila ditekan kembali ke bentuk semula, spt bola karet)');
INSERT INTO KNTLword VALUES(114,'KINTAL','katak yg dapat menggembungkan perutnya');
INSERT INTO KNTLword VALUES(115,'KINTAR','kintar ');
INSERT INTO KNTLword VALUES(116,'KINTIL','ikut dl perjalanan');
INSERT INTO KNTLword VALUES(117,'KLOTOK','yg berbicara atau yg menulis (dl ragam akrab)');
INSERT INTO KNTLword VALUES(118,'KOAGEL','gel yg terbentuk dl proses koagulasi');
INSERT INTO KNTLword VALUES(120,'KOMBOR','longgar (tt celana)');
INSERT INTO KNTLword VALUES(121,'KOMPON','halaman tertutup');
INSERT INTO KNTLword VALUES(122,'KOMPOR','perapian untuk memasak yg menggunakan minyak tanah, gas, atau listrik sbg bahan bakar');
INSERT INTO KNTLword VALUES(123,'KOMPOS','pupuk campuran yg terdiri atas bahan organik (spt daun dan jerami yg membusuk) dan kotoran hewan');
INSERT INTO KNTLword VALUES(124,'KONDAI','mencopot, menanggalkan, melepaskan sesuatu untuk orang lain');
INSERT INTO KNTLword VALUES(125,'KONDOR','burut');
INSERT INTO KNTLword VALUES(126,'KONFER','permainan bola yg dilakukan oleh dua regu, masing');
INSERT INTO KNTLword VALUES(127,'KONGKO','bercakap');
INSERT INTO KNTLword VALUES(128,'KONGKR','penjagaan');
INSERT INTO KNTLword VALUES(129,'KONGSI','persekutuan dagang');
INSERT INTO KNTLword VALUES(130,'KONIUM','anyaman dr bilah bambu (untuk dinding dsb)');
INSERT INTO KNTLword VALUES(131,'KONJEN','terbangai (ter.ba.ngai), terbengkalai');
INSERT INTO KNTLword VALUES(132,'KONKAF','cekung');
INSERT INTO KNTLword VALUES(133,'KONKUR','gerak turun naik (pd urat nadi, ubun');
INSERT INTO KNTLword VALUES(134,'KONOID','<i>Dok</i> kelenjar di tengah otak');
INSERT INTO KNTLword VALUES(135,'KONOMI','membantah pendapat orang lain dng mengajukan alasan');
INSERT INTO KNTLword VALUES(136,'KONPER','pucuk pimpinan gereja Huria Kristen Batak Protestan (HKBP)');
INSERT INTO KNTLword VALUES(137,'KONSEP','rancangan atau buram surat dsb');
INSERT INTO KNTLword VALUES(138,'KONSER','pertunjukan musik di depan umum');
INSERT INTO KNTLword VALUES(139,'KONSOL','balok yg satu ujungnya terpasang pd suatu penopang tetap dan ujung lainnya bebas');
INSERT INTO KNTLword VALUES(140,'KONSUL','orang yg diangkat dan ditugasi sbg wakil pemerintah suatu negara dl mengurus kepentingan perdagangan atau perihal warganegaranya di negara lain');
INSERT INTO KNTLword VALUES(141,'KONSUM','terlalai');
INSERT INTO KNTLword VALUES(142,'KONTAK','hubungan satu dng yg lain');
INSERT INTO KNTLword VALUES(143,'KONTAL','misal');
INSERT INTO KNTLword VALUES(144,'KONTAN','tunai (tt pembayaran)');
INSERT INTO KNTLword VALUES(145,'KONTEN','mengajukan perkara dsb (kpd hakim, orang yg berkuasa)');
INSERT INTO KNTLword VALUES(146,'KONTER','melawan');
INSERT INTO KNTLword VALUES(147,'KONTES','perlombaan (kecantikan dsb)');
INSERT INTO KNTLword VALUES(148,'KONTET','tidak dapat tumbuh menjadi besar');
INSERT INTO KNTLword VALUES(149,'KONTIN','burung yg warna bulunya biru kehitam');
INSERT INTO KNTLword VALUES(150,'KONTRA','dl keadaan tidak setuju');
INSERT INTO KNTLword VALUES(151,'KONTUR','garis bentuk');
INSERT INTO KNTLword VALUES(152,'KONVOI','iring');
INSERT INTO KNTLword VALUES(153,'KONYAK','brendi Prancis berkualitas terbaik');
INSERT INTO KNTLword VALUES(154,'KONYAL','markisa');
INSERT INTO KNTLword VALUES(155,'KONYAN','perayaan tahun baru Cina');
INSERT INTO KNTLword VALUES(156,'KONYOL','tidak sopan');
INSERT INTO KNTLword VALUES(157,'KOPBAL','sundulan thd bola (dl sepak bola)');
INSERT INTO KNTLword VALUES(158,'KOPRAL','pangkat golongan tamtama dl ketentaraan, satu tingkat di bawah bintara dan satu tingkat di atas prajurit, yg mencakupi kopral kepala, kopral satu, dan kopral dua');
INSERT INTO KNTLword VALUES(159,'KOPROK','permainan dadu kocok');
INSERT INTO KNTLword VALUES(160,'KOPROL','gerakan berguling ke depan');
INSERT INTO KNTLword VALUES(161,'KOPYOK','mengopyok (me.ngop.yok), mengocok');
INSERT INTO KNTLword VALUES(162,'KOPYOR','lunak dan hancur (tt bagian daging kelapa)');
INSERT INTO KNTLword VALUES(163,'KORDON','garis pelindung');
INSERT INTO KNTLword VALUES(164,'KORION','<i>Dok</i> selaput terluar pembungkus janin');
INSERT INTO KNTLword VALUES(165,'KORNEL','kolonel');
INSERT INTO KNTLword VALUES(166,'KORPUL','raja');
INSERT INTO KNTLword VALUES(167,'KORSEL','kuda');
INSERT INTO KNTLword VALUES(168,'KORWIL','bergairah, bersemangat');
INSERT INTO KNTLword VALUES(169,'KOSMOS','jagat raya');
INSERT INTO KNTLword VALUES(170,'KOSTUM','pakaian khusus (dapat pula merupakan pakaian seragam) bagi perseorangan, regu olahraga, rombongan, kesatuan, dsb dl upacara, pertunjukan, dsb');
INSERT INTO KNTLword VALUES(171,'KRATON','banyak cakap');
INSERT INTO KNTLword VALUES(172,'KRESOL','zat antiseptik turunan fenol yg diperoleh dr dl ter batubara');
INSERT INTO KNTLword VALUES(173,'KTATOR','bermacam');
INSERT INTO KNTLword VALUES(174,'KUATOR','proses, cara, perbuatan membeberkan');
INSERT INTO KNTLword VALUES(175,'KUNTAU','pencak cara Cina');
INSERT INTO KNTLword VALUES(176,'KUNTIT','menguntit (me.ngun.tit), mengikut (dr belakang)');
INSERT INTO KNTLword VALUES(177,'KUNTUL','tidak berekor');
INSERT INTO KNTLword VALUES(178,'KUNTUM','kuncup bunga yg hampir mekar (berkembang');
INSERT INTO KNTLword VALUES(179,'KUSTOS','cairan tidak berwarna yg mudah menguap, mudah terbakar, dipakai dl industri dan pengobatan, merupakan unsur ramuan yg memabukkan dl kebanyakan minuman keras');
INSERT INTO KNTLword VALUES(180,'LENTOK','terkulai ke sisi (spt sumbu pelita, spt kepala orang yg pingsan)');
INSERT INTO KNTLword VALUES(181,'LONCOS','semakin ke ujung semakin runcing (spt kerucut)');
INSERT INTO KNTLword VALUES(182,'LONDON','telah dibaca');
INSERT INTO KNTLword VALUES(183,'LONGOK','melongok (me.lo.ngok), melihat dng mengeluarkan kepala (melalui jendela dsb)');
INSERT INTO KNTLword VALUES(184,'LONJOR','batang (kata penggolong bagi barang yg panjang)');
INSERT INTO KNTLword VALUES(185,'LONTAI','melontai (me.lon.tai), berkeluk (tt garis dsb)');
INSERT INTO KNTLword VALUES(186,'LONTAK','pemberi ampun');
INSERT INTO KNTLword VALUES(187,'LONTAR','melontar (me.lon.tar), melempar');
INSERT INTO KNTLword VALUES(188,'LONTOK','pendek dan besar (gemuk)');
INSERT INTO KNTLword VALUES(189,'LONTOS','berkenaan dng dekorasi');
INSERT INTO KNTLword VALUES(190,'LONYOK','lodoh kena api atau siraman air panas');
INSERT INTO KNTLword VALUES(191,'MANTEL','baju panjang (biasanya dr bahan kain tebal), berlengan atau tidak berlengan untuk menyelubungi tubuh');
INSERT INTO KNTLword VALUES(192,'MANTOL','mantol ');
INSERT INTO KNTLword VALUES(193,'MANTUL','hawa panas yg terjadi krn nyala api atau dr panas tubuh');
INSERT INTO KNTLword VALUES(194,'MENTAL','terpelanting');
INSERT INTO KNTLword VALUES(195,'MENTOK','terantuk (pd)');
INSERT INTO KNTLword VALUES(196,'MENTOL','terna tahunan, suku <i>Lamiaceae</i> yg membentuk stolon, bagian tanaman seluruhnya mengandung minyak asiri yg berbau harum dan dapat diekstrak dng penyulingan, setelah didinginkan menghasilkan mentol');
INSERT INTO KNTLword VALUES(197,'MENTOR','pembimbing atau pengasuh (biasanya untuk mahasiswa)');
INSERT INTO KNTLword VALUES(198,'MENTUL','perhiasan yg dipasang pd rambut atau sanggul, berupa tusuk sanggul bertangkai panjang dng hiasan kuntum bunga bermata (intan, berlian, atau permata imitasi) pd bagian atasnya dan dapat bergerak berayun');
INSERT INTO KNTLword VALUES(199,'MONCOR','mengalir ke luar');
INSERT INTO KNTLword VALUES(200,'MONDOK','pendek gemuk (tt bentuk sesuatu)');
INSERT INTO KNTLword VALUES(201,'MONGOL','perihal bagus');
INSERT INTO KNTLword VALUES(202,'MONIAL','tumbuhan yg seratnya dibuat tali belati');
INSERT INTO KNTLword VALUES(203,'MONROE','alat untuk membelah');
INSERT INTO KNTLword VALUES(204,'MONTIR','orang yg pekerjaannya memasang, memperbaiki, dsb mesin kendaraan bermotor, dsb yg rusak');
INSERT INTO KNTLword VALUES(205,'MONTIT','lokomotif kereta api perkebunan');
INSERT INTO KNTLword VALUES(206,'MONTOK','gemuk berisi');
INSERT INTO KNTLword VALUES(207,'MONYOS','mendapat malu (krn kalah dsb)');
INSERT INTO KNTLword VALUES(208,'MUNTUL','tumpul');
INSERT INTO KNTLword VALUES(209,'NAFTOL','<i>Kim</i> zat kristal antiseptik C10H7OH dr ter batu bara, terdapat dl dua bentuk, alfa dan beta');
INSERT INTO KNTLword VALUES(210,'NONGOL','muncul, datang');
INSERT INTO KNTLword VALUES(211,'NONTAX','sudah diberi taji');
INSERT INTO KNTLword VALUES(212,'NONTES','batang kayu yg berkait untuk melilitkan ujung tali pd benda tsb');
INSERT INTO KNTLword VALUES(213,'NONTON','bersifat sangat berhati');
INSERT INTO KNTLword VALUES(214,'PANTUL','memantul (me.man.tul), menganjal (spt bola dilemparkan ke dinding)');
INSERT INTO KNTLword VALUES(215,'PENTAL','terpental (ter.pen.tal), terpelanting jauh');
INSERT INTO KNTLword VALUES(216,'PENTOL','sesuatu (bentuk) yg menonjol (agak besar)');
INSERT INTO KNTLword VALUES(217,'PESTOL','pistol');
INSERT INTO KNTLword VALUES(218,'PINTAL','berpintal (ber.pin.tal), berpilin (tt tali, dawai, dsb)');
INSERT INTO KNTLword VALUES(219,'PINTIL','untingan benang');
INSERT INTO KNTLword VALUES(220,'PISTOL','senjata api genggam yg pendek dan kecil');
INSERT INTO KNTLword VALUES(221,'PODSOL','proses, cara, perbuatan mengadopsi');
INSERT INTO KNTLword VALUES(222,'POKROL','pembela atau wakil orang yg beperkara (dl pengadilan)');
INSERT INTO KNTLword VALUES(223,'PONDOH','nama salak yg daging buahnya empuk, spt embut, rasanya tidak sepet dan tidak masam');
INSERT INTO KNTLword VALUES(224,'PONDOK','bangunan untuk tempat sementara (spt yg didirikan di ladang, di hutan, dsb)');
INSERT INTO KNTLword VALUES(225,'PONSEL','bersifat degenerasi');
INSERT INTO KNTLword VALUES(226,'PONTEN','angka (biji, nilai) kepandaian atau angka pertandingan (perlombaan)');
INSERT INTO KNTLword VALUES(227,'PONTOH','gelang besar dr emas atau perak yg berukir naga atau merak yg dipakai di lengan atas (di atas siku) atau di atas pergelangan tangan');
INSERT INTO KNTLword VALUES(228,'PONTON','sampan yg rendah dan lebar untuk menggalang atau menyangga jembatan darurat dsb');
INSERT INTO KNTLword VALUES(229,'PORTAL','pintu gerbang');
INSERT INTO KNTLword VALUES(230,'POSTEL','bebas dr gangguan penyimpangan warna');
INSERT INTO KNTLword VALUES(231,'PUNTAL','berpuntal');
INSERT INTO KNTLword VALUES(232,'PUNTUL','tumpul');
INSERT INTO KNTLword VALUES(233,'RENTAL','persewaan');
INSERT INTO KNTLword VALUES(234,'RONDOK','berondok (be.ron.dok), bersembunyi dng berjongkok di balik semak dsb');
INSERT INTO KNTLword VALUES(235,'RONGOS','merongos (me.ro.ngos), mudah (lekas) marah');
INSERT INTO KNTLword VALUES(236,'RONGOT','rongot ');
INSERT INTO KNTLword VALUES(237,'RONTAL','proses, cara, perbuatan mencarter');
INSERT INTO KNTLword VALUES(238,'RONTEK','bendera kecil yg dihiaskan pd tombak');
INSERT INTO KNTLword VALUES(239,'RONTOK','jatuh atau gugur dl jumlah yg banyak (tt buah');
INSERT INTO KNTLword VALUES(240,'RONYOK','renyuk');
INSERT INTO KNTLword VALUES(241,'SENTAL','menyental (me.nyen.tal), menggosok kuat');
INSERT INTO KNTLword VALUES(242,'SENTIL','tampak tersembul sedikit di antara bibir (sugi, gula');
INSERT INTO KNTLword VALUES(243,'SENTOL','pendek atau gemuk');
INSERT INTO KNTLword VALUES(244,'SENTUL','pohon, buahnya dapat dimakan, masam rasanya, kayunya dibuat papan');
INSERT INTO KNTLword VALUES(245,'SINEOL','enkaliptol');
INSERT INTO KNTLword VALUES(246,'SINTAL','gemuk padat atau padat berisi (tt tubuh)');
INSERT INTO KNTLword VALUES(247,'SINTIL','mengaduh dng tiba');
INSERT INTO KNTLword VALUES(248,'SISTOL','perantara');
INSERT INTO KNTLword VALUES(249,'SOFBOL','meminta pertolongan (ditolong oleh) bidan waktu melahirkan (anak)');
INSERT INTO KNTLword VALUES(250,'SOMBOL','menyombol (me.nyom.bol), menyuapi (makanan dsb) dng paksa');
INSERT INTO KNTLword VALUES(251,'SONDOK','gombak di dahi');
INSERT INTO KNTLword VALUES(252,'SONDOL','sondol ');
INSERT INTO KNTLword VALUES(253,'SONGEL','tersongel');
INSERT INTO KNTLword VALUES(254,'SONTAK','sompek');
INSERT INTO KNTLword VALUES(255,'SONTEK','menyontek');
INSERT INTO KNTLword VALUES(256,'SONTOK','pendek');
INSERT INTO KNTLword VALUES(257,'SOSIOL','menjadi abu');
INSERT INTO KNTLword VALUES(258,'SOSPOL','paham (sifat) lebih memperhatikan dan mengutamakan kepentingan orang lain (kebalikan dr egoisme)');
INSERT INTO KNTLword VALUES(259,'SUNTIL','permainan anak kecil dng cara menutup dan membuka mata');
INSERT INTO KNTLword VALUES(260,'TOKTOK','batang kayu yg berongga (terdapat di surau dsb) yg dipukul untuk memanggil orang agar salat, berkumpul, dsb');
INSERT INTO KNTLword VALUES(261,'TOMBOL','alat (knop) pd mesin dsb, yg gerak tekan atau gerak tariknya dapat menjalankan, menghentikan, atau mengubah gerak pd mesin');
INSERT INTO KNTLword VALUES(262,'TONGOL','menongol (me.no.ngol), menyembulkan kepala');
INSERT INTO KNTLword VALUES(263,'TONJOK','tinju');
INSERT INTO KNTLword VALUES(264,'TONJOL','jendul (di kulit, di dahi, dsb)');
INSERT INTO KNTLword VALUES(265,'TONSIL','amandel');
INSERT INTO KNTLword VALUES(266,'TONTON','menonton (me.non.ton), melihat (pertunjukan, gambar hidup, dsb)');
INSERT INTO KNTLword VALUES(267,'TORTOR','tarian suku Batak yg dilakukan pd upacara menggali tulang');
INSERT INTO KNTLword VALUES(268,'WORTEL','tanaman sayuran berakar pasak berdaging, berwarna kuning jingga, kaya akan zat gula, vitamin, dan garam mineral');
COMMIT;
